#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: stylish
# File Options
files:
  include: 'src/**/*.s+(a|c)ss'
  ignore:
    - './node_modules/**/*.*'
# Rule Configuration
# # number 2-error, 1-warn
rules:

  attribute-quotes: 2
  border-zero:
    - 2
    -
      convention: 0
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  function-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length: 2
  hex-notation:
    - 2
    -
      style: lowercase
  id-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  indentation:
    - 2
    -
      size: 2
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-css-comments: 2
  no-debug: 1
  no-duplicate-properties: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-misspelled-properties: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-universal-selectors: 2
  no-url-protocols: 2
  no-warn: 1
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  property-sort-order:
    - 2
    -
      order: 'smacss'
      ignore-custom-properties: true
  pseudo-element: 2
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 2
