language: node_js

node_js:
- '4'
- '5'
- '6'

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_05591fa2c311_key -iv $encrypted_05591fa2c311_iv -in ./id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
- chmod 600 ~/.ssh/id_ecdsa
- ssh-keyscan -t ecdsa -p $PRODUCTION_PORT -H $PRODUCTION_HOST 2>/dev/null >> ~/.ssh/known_hosts

before_script:
- npm install
- npm run build

script:
- npm test
- echo 'eliminating unnecessary files..'
- echo 'bin/' > .gitignore
- rm -rf 'maps/'
- rm -rf 'node_modules/'
- rm -rf 'src/'
- rm '.babelrc'
- rm '.editorconfig'
- rm '.eslintignore'
- rm '.eslintrc.json'
- rm '.sass-lint.yml'
- rm '.travis.yml'
- rm 'circle.yml'
- rm 'gulpfile.babel.js'
- rm 'id_ecdsa.enc'
- rm 'id_ecdsa.pub'
- rm 'package.json'
- bash ./bin/travis-deploy.sh "gh-pages" "$TRAVIS_NODE_VERSION" "6"

env:
  global:
    #travis encrypt PRODUCTION_USER=user PRODUCTION_HOST=host PRODUCTION_PORT=port PRODUCTION_DIR=dir
    secure: "Sl+vpvDKDPhGo/HLdV06cNMFVNzmhqU+EMhh9DOZh2lZV1kTsRXMyfOH0jHsfwo/LAj/p8LL2mX+hwkTkgnPX0P9+uHGgUYXm/vl7KJiklz/WuQlUXZ35L0jZKUknOcleKjMQ/H8bqaQDkac3GqqfPInCEiVKYuPvRIzk7Ukwsg/Lz7qQt0oeFIR2qEnUTkWbp1UaYuYWuo0SIlQHbvcZe2MdW3yAnM/IMlLTVg4fffIQl+vFetCpG8OMZ5y3fMO9faPke8IM7KY1BlkfugTXg/mI7INkUqXhPp1guimnHHj3gRUmtAo8sWIxj9Ekpt6+yFmuBcN+DJ7CLi3uhUB7Vuw/sAlJI8YmmHubcvxOdUW3IK+gs9VOlMNCdtnAwmEpTF60GVcuVjnFyYuMP7Vvql34MzyrnTVmVN+h4ILhBr6VUQC4cHBMuGUTGi6AMXr84Q2/jGkoWO2Ts94lyxSouWoFW5L0RFdCiU8cSkLXBR7yRgqdQ9EAZ5QZe6VMTwsW7NsWZvTWfQsOTFEH1thBDoRsH6f9IWkIJr8I4DfGqS63aBtJoG+fkx3A3z06Tfx7Xx8WmSHWjIPUjloBkb3DpHOW3VdVhPTSWT3NcU54TI6p7D6J9Odo65r2SczKbzzeyCVFTtITWead9n6t/DPHw8kmo1y5vKrfM4Jd0h8+1Q="
