language: node_js
node_js:
- '6'
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"
before_script:
- npm run build
script:
- npm run lint
# after_success:
# - curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/deploy-gh-pages.sh | bash
# env:
#   global:
#   - NODE_VERSION_TO_DEPLOY: 6
#   - GH_REF: github.com/wakayamarb/wakayamarb.org
