language: node_js
node_js:
- '6'
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_install:
- openssl aes-256-cbc -K $encrypted_05591fa2c311_key -iv $encrypted_05591fa2c311_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh.id_rsa

before_script:
- npm run build

script:
- npm run lint

after_success:
- rm -rf .git/
- rm -rf bin/
- rm -rf maps/
- rm -rf node_modules/
- rm -rf src/
- rm .*
- rm gulpfile.babel.js
- rm id_rsa.enc
- rm id_rsa.pub
- rm package.json
- git init
- git config user.name "kamataryo"
- git config user.email "kamataryo@travis-ci.org"
- git remote add origin git@github.com:wakayamarb/wakayamarb.org.git
- git add .
- git commit -m"Deploy from travis"
- git push --force origin gh-pages
