language: node_js
node_js:
- '6'
notifications:
  email:
    on_success: never
    on_failure: change

before_install:
- openssl aes-256-cbc -K $encrypted_05591fa2c311_key -iv $encrypted_05591fa2c311_iv -in id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
- chmod 600 ~/.ssh/id_ecdsa

before_script:
- npm run build

script:
- npm run lint

after_success:
- echo 'Removing unnecessary files..'
- rm -rf bin/
- rm -rf maps/
- rm -rf node_modules/
- rm -rf src/
- rm .*
- rm gulpfile.babel.js
- rm id_rsa.enc
- rm id_rsa.pub
- rm package.json
- bash ./bin/deploy.sh
