language: node_js

node_js:
- '4'
- '5'
- '6'

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_05591fa2c311_key -iv $encrypted_05591fa2c311_iv -in ./id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
- chmod 600 ~/.ssh/id_ecdsa

before_script:
- npm install
- npm run build

script:
- npm test
- echo 'eliminating unnecessary files..'
- echo 'bin/' > .gitignore
- rm -rf 'maps/'
- rm -rf 'node_modules/'
- rm -rf 'src/'
- rm '.babelrc'
- rm '.editorconfig'
- rm '.eslintignore'
- rm '.eslintrc.json'
- rm '.sass-lint.yml'
- rm '.travis.yml'
- rm 'gulpfile.babel.js'
- rm 'id_ecdsa.enc'
- rm 'id_ecdsa.pub'
- rm 'package.json'
- bash ./bin/travis-deploy.sh "gh-pages" "$TRAVIS_NODE_VERSION" "6"

env:
  global:
    secure: "uqVYsIwz0sb7k63+jQy+q0BVewOR+Qj1iqSnpRQftzaiyxOCthYN5o5c8o38KLwJhZQwMQs0EMamC7YLeYaX1AvWsQkKLYo8pUHjP6UmNl9+51YL1LZvw5Lk6aDpnN8njjl8+uEJxi7TGRr4hpVhRhM+Ld/+1b30E4ztpF+ylxwSz0h/kiPWcyOOyvIWuZO1thSX2km/7o3Fg+3LHNu0+jhv7QYv3Oq8/VOyYQdCtf713qns9zvjRXvqQfRwSRu3xE4mm9HiN4hl1p1ItAKELZ2Z9YkmaqznNyidylwCQsJvFkW5oGyM5zqBHtFjm6ZTlw56s1zCCWoQ+7K2J1Ou1St0OxwAS4EnTrxLVTX6AsaDuMunNlprmXTPNFi1IWUdJ8nCC1HfxlsHzfp31/5P58/i/YcZwF2YyMgE/vuJXdgBJsS8iAVttC1uEQUWd3lnD3jQmQ0F0TzN35qVdgvgTVOT6GPrXlxBJhd4tNZLlrBQ/T6kNoq7Bmg+5+Lg4BhDc0rWtJq3H1rg8Wb//hOn3mCNpACtDCQ7Q8lANjADk/mjgYriTrgIvHhhBTvzpBGD7T65vK1xm6dU50zTaeIGRGbnGdOFBxCgz1VE8pkEZDdWAunkfHbfeo48wL8JSB9v8j+g9tHPTtH1k60L4xCZV30rSq3TnqHlM3XHzKzYuz4="
