language: node_js

node_js:
- '4'
- '5'
- '6'

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_05591fa2c311_key -iv $encrypted_05591fa2c311_iv -in ./id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
- chmod 600 ~/.ssh/id_ecdsa

before_script:
- npm install
- npm run build

script:
- npm test
- echo 'eliminating unnecessary files..'
- echo 'bin/' > .gitignore
- rm -rf 'maps/'
- rm -rf 'node_modules/'
- rm -rf 'src/'
- rm '.babelrc'
- rm '.editorconfig'
- rm '.eslintignore'
- rm '.eslintrc.json'
- rm '.sass-lint.yml'
- rm '.travis.yml'
- rm 'gulpfile.babel.js'
- rm 'id_ecdsa.enc'
- rm 'id_ecdsa.pub'
- rm 'package.json'
- bash ./bin/travis-deploy.sh "gh-pages" "$TRAVIS_NODE_VERSION" "6"

env:
  global:
    secure: "onvqxk9yMOB0QBgDuvpXTIFhTzcB/UgWCCYP+JsvzioB/0d9sNRQ4G32sDyT7DKf8zR2VT88CagpwAgmKhfZoQAfFvmAiilhtVnDzw4sya5ChibjybZG5cdza2dZtlCoKmH7S2ZM10d1n7tgo9cVBPNdvDDqJcdugXEkxu7ip8vCo05agndxdejteNcusvmS11G9a1dHoo9GioFAu7wl0eV+QAa+DxXFxfKWH3Li+PbGsbbcBjnt62r6eKH2WTkT1exsYJ26hKLd1x504NPYJNMAM1gZvicD3HjDQCl65L9X0DLdkAVBWzB3SVk5jG17pn3zpj2QlsmmIUM4amt4Nj86pL0ldIPxR9Z5zLA4N3p8ZzJ42BZpDyJuk98taOpi/J8vkZJMpdg7eaECTbDbgU3Zs5ZLHGzFsBPwR+41okXXTUywbWxcJUubqVVrFltL98QS6rXXRmZV42JhSDQzV3u/ETHsynTH0bIIpzi3G5wxqCfUb5uVrq+JU4EY2govSJ7X8VAuedi+Y3yMigsFXwdq3AMQRek0uGVf1t6e7FxJW9jqHsFkmBELykrsSkgMyi0MeMwvx5UxwkTOr0Q3QjX+NuNZw87cF6KSPoIL+YDOWgqAiceTQ/QNlwkEDajfAeun61UL15xOscbIufrWQmk5VSqxNGgDPM9jPjjhkcs="
