language: node_js

node_js:
- '4'
- '5'
- '6'
- '7'

before_install:
- openssl aes-256-cbc -K $encrypted_05591fa2c311_key -iv $encrypted_05591fa2c311_iv -in id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
- chmod 600 ~/.ssh/id_ecdsa

before_script:
- npm run build

script:
- npm run lint

after_success:
- echo 'bin/'              > .gitignore
- echo 'maps/'             >> .gitignore
- echo 'node_modules/'     >> .gitignore
- echo 'src/'              >> .gitignore
- echo '.babelrc'          >> .gitignore
- echo '.editorconfig'     >> .gitignore
- echo '.eslingignore'     >> .gitignore
- echo '.eslintrc.json'    >> .gitignore
- echo 'sass-lint.yml'     >> .gitignore
- echo '.travis.yml'       >> .gitignore
- echo 'gulpfile.babel.js' >> .gitignore
- echo 'id_rsa.enc'        >> .gitignore
- echo 'id_rsa.pub'        >> .gitignore
- echo 'package.json'      >> .gitignore
- bash ./bin/deploy.sh "gh-pages" "$TRAVIS_NODE_VERSION" "7"
